export const ACTIVITY_TYPE_MATCH = 'match'
export const ACTIVITY_TYPE_UNMATCH = 'unmatch'
export const ACTIVITY_TYPE_PROFILE_VIEW = 'profile-view'
export const ACTIVITY_TYPE_CONNECT = 'connect'
export const ACTIVITY_TYPE_DISCONNECT = 'disconnect'
export const ACTIVITY_TYPE_REPORT = 'report'
export const ACTIVITY_TYPE_BLOCK = 'block'
