export const LOGIN_START = '@user/LOGIN_START'
export const LOGIN_SUCCESS = '@user/LOGIN_SUCCESS'
export const LOGIN_ERROR = '@user/LOGIN_ERROR'

export const PASSWORD_RESET_START = '@user/PASSWORD_RESET_START'
export const PASSWORD_RESET_SUCCESS = '@user/PASSWORD_RESET_SUCCESS'
export const PASSWORD_RESET_ERROR = '@user/PASSWORD_RESET_ERROR'

export const NEW_PASSWORD_START = '@user/NEW_PASSWORD_START'
export const NEW_PASSWORD_SUCCESS = '@user/NEW_PASSWORD_SUCCESS'
export const NEW_PASSWORD_ERROR = '@user/NEW_PASSWORD_ERROR'

export const VERIFY_ACCOUNT_START = '@user/VERIFY_ACCOUNT_START'
export const VERIFY_ACCOUNT_SUCCESS = '@user/VERIFY_ACCOUNT_SUCCESS'
export const VERIFY_ACCOUNT_ERROR = '@user/VERIFY_ACCOUNT_ERROR'

export const ME_START = '@user/ME_START'
export const ME_SUCCESS = '@user/ME_SUCCESS'
export const ME_ERROR = '@user/ME_ERROR'

export const LOGOUT = '@user/LOGOUT'

export const MENU_OPEN = '@menu/OPEN'
export const MENU_CLOSE = '@menu/CLOSE'

export const USER_UPDATE_START = '@user/USER_UPDATE_START'
export const USER_UPDATE_SUCCESS = '@user/USER_UPDATE_SUCCESS'
export const USER_UPDATE_ERROR = '@user/USER_UPDATE_ERROR'

export const POTENTIAL_MATCHES_START = '@user/POTENTIAL_MATCHES_START'
export const POTENTIAL_MATCHES_SUCCESS = '@user/POTENTIAL_MATCHES_SUCCESS'
export const POTENTIAL_MATCHES_ERROR = '@user/POTENTIAL_MATCHES_ERROR'

export const CONNECTED_MATCH_START = '@connectedMatch/CONNECTED_MATCH_START'
export const CONNECTED_MATCH_SUCCESS = '@connectedMatch/CONNECTED_MATCH_SUCCESS'
export const CONNECTED_MATCH_ERROR = '@connectedMatch/CONNECTED_MATCH_ERROR'

export const CONNECT_MATCH_START = '@connectedMatch/CONNECT_MATCH_START'
export const CONNECT_MATCH_SUCCESS = '@connectedMatch/CONNECT_MATCH_SUCCESS'
export const CONNECT_MATCH_ERROR = '@connectedMatch/CONNECT_MATCH_ERROR'

export const DISCONNECT_MATCH_START = '@connectedMatch/DISCONNECT_MATCH_START'
export const DISCONNECT_MATCH_SUCCESS = '@connectedMatch/DISCONNECT_MATCH_SUCCESS'
export const DISCONNECT_MATCH_ERROR = '@connectedMatch/DISCONNECT_MATCH_ERROR'

export const MATCHES_LOAD_START = '@matches/MATCHES_LOAD_START'
export const MATCHES_LOAD_SUCCESS = '@matches/MATCHES_LOAD_SUCCESS'
export const MATCHES_LOAD_ERROR = '@matches/MATCHES_LOAD_ERROR'

export const MATCHES_SET_SELECTED_MATCH = '@matches/MATCHES_SET_SELECTED_MATCH'

export const ROOMMESSAGES_DUMP_MESSAGES = '@roomMessage/ROOMMESSAGES_DUMP_MESSAGES'
export const SET_NEW_ROOMMESSAGE = '@roomMessage/SET_NEW_ROOMMESSAGE'
export const ROOMMESSAGES_LOAD_START = '@roomMessage/ROOMMESSAGES_LOAD_START'
export const ROOMMESSAGES_LOAD_SUCCESS = '@roomMessage/ROOMMESSAGES_LOAD_SUCCESS'
export const ROOMMESSAGES_LOAD_ERROR = '@roomMessage/ROOMMESSAGES_LOAD_ERROR'

export const ACTIVITIES_SET_NEW = '@activities/ACTIVITIES_SET_NEW'
export const ACTIVITIES_LOAD_START = '@activities/ACTIVITIES_LOAD_START'
export const ACTIVITIES_LOAD_SUCCESS = '@activities/ACTIVITIES_LOAD_SUCCESS'
export const ACTIVITIES_LOAD_ERROR = '@activities/ACTIVITIES_LOAD_ERROR'

export const ACTIVITIES_SEEN_START = '@activities/ACTIVITIES_SEEN_START'
export const ACTIVITIES_SEEN_SUCCESS = '@activities/ACTIVITIES_SEEN_SUCCESS'
export const ACTIVITIES_SEEN_ERROR = '@activities/ACTIVITIES_SEEN_ERROR'

export const BLOCK_MATCH_START = '@blockedUsers/BLOCK_MATCH_START'
export const BLOCK_MATCH_SUCCESS = '@blockedUsers/BLOCK_MATCH_SUCCESS'
export const BLOCK_MATCH_ERROR = '@blockedUsers/BLOCK_MATCH_ERROR'

export const REPORT_MATCH_START = '@reportedUsers/REPORT_MATCH_START'
export const REPORT_MATCH_SUCCESS = '@reportedUsers/REPORT_MATCH_SUCCESS'
export const REPORT_MATCH_ERROR = '@reportedUsers/REPORT_MATCH_ERROR'

export const SET_ONLINE_USERS = '@online-users/SET_ONLINE_USERS'

export const SET_SELECTED_POTENTIAL_MATCH = '@user/SET_SELECTED_POTENTIAL_MATCH'
