export const EVENT_TYPE_MATCH = 'match'
export const EVENT_TYPE_UNMATCH = 'unmatch'
export const EVENT_TYPE_MESSAGE = 'message'
export const EVENT_TYPE_PROFILE_VIEW = 'profile-view'
export const EVENT_TYPE_CONNECT = 'connect'
export const EVENT_TYPE_BLOCK = 'block'
export const EVENT_TYPE_UNBLOCK = 'unblock'
